"""foreign key

Revision ID: bd0ddd1bf85b
Revises: 9f4e1010ddd4
Create Date: 2021-07-25 12:34:10.630727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0ddd1bf85b'
down_revision = '9f4e1010ddd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewardsoutput')
    op.create_foreign_key(None, 'rewards_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rewards_list', type_='foreignkey')
    op.create_table('rewardsoutput',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
